name: Deploy to Salesforce Production
on:
  pull_request:
    types: [opened,reopened]
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: |
          npm install -g sfdx-cli
          #npm install gfarb/sfdx-deploy@v1
          
      - name: 'Populate auth file with DEVHUB_SFDX_URL and DEVHUB_SFDX_AUTH_URL secrets'
        shell: bash
        run: |
            echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
            secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
            if [ $secretFileSize == 1 ]; then
                echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
                exit 1;
            fi

      - name: Authenticate Dev Hub
        run: |
          sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -d -a devhub

      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: devhub
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes
          TEST_LEVEL: RunLocalTests
          WAIT: 200
          FLAGS: --checkOnly
