on:
  push:
    branches:
      - Actions

name: Validate Salesforce Metadata

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate Dev Hub
        run: |
          echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
          sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d

      - name: Validate Code
        run: |
          sfdx force:source:validate -p force-app
